name: Flamegraph Benchmark and Deploy
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  flamegraph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release
      run: cargo build --release

    - name: Install Flamegraph.rs
      run: cargo install flamegraph

    - name: Run Flamegraph
      run: |
        mkdir -p docs/src
        # Generate flamegraph for the file MetadataService2.cls
        cargo flamegraph --output docs/src/flamegraph.svg -- ./target/release/afmt -f large_apex_files/files/MetadataService2.cls

    - name: Setup mdBook for Flamegraph
      run: |
        mkdir -p docs/src
        echo '[book]' > docs/book.toml
        echo 'title = "AFMT Benchmark and Profiling Results"' >> docs/book.toml
        echo '[output.html]' >> docs/book.toml
        echo 'site-url = "/afmt/"' >> docs/book.toml
        echo '# Summary' > docs/src/SUMMARY.md
        echo '- [Flamegraph Results](flamegraph.md)' >> docs/src/SUMMARY.md

    - name: Embed Flamegraph in GitHub Pages
      run: |
        echo '<img src="flamegraph.svg" alt="Flamegraph" />' > docs/src/flamegraph.md

    - name: Install mdBook
      run: cargo install mdbook

    - name: Build mdBook
      run: |
        cd docs
        mdbook build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/book

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Update flamegraph and build mdBook" || echo "No changes to commit"
        git push origin HEAD:main

  deploy:
    needs: flamegraph
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

