name: Flamegraph Benchmark and mdBook Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flamegraph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release
      run: cargo build --release

    - name: Install Flamegraph.rs
      run: cargo install flamegraph

    - name: Install Perf (for Flamegraph)
      run: sudo apt-get install linux-tools-common linux-tools-generic linux-tools-`uname -r`

    - name: Download large Apex file
      run: |
        git clone https://github.com/xixiaofinland/large_apex_files
        ls large_apex_files/files

    - name: Generate Flamegraph
      run: |
        sudo perf record --call-graph=dwarf ./target/release/afmt -f large_apex_files/files/MetadataService2.cls
        sudo perf script | flamegraph > flamegraph.svg

    - name: Create mdBook for Flamegraph
      run: |
        mkdir -p docs/src
        cp flamegraph.svg docs/src/
        echo '# Flamegraph Results' > docs/src/flamegraph.md
        echo '![Flamegraph](flamegraph.svg)' >> docs/src/flamegraph.md
        echo '[book]' > docs/book.toml
        echo 'title = "AFMT Flamegraph Results"' >> docs/book.toml
        echo 'src = "src"' >> docs/book.toml
        echo '[output.html]' >> docs/book.toml
        echo 'site-url = "/afmt/"' >> docs/book.toml
        echo '# Summary' > docs/src/SUMMARY.md
        echo '- [Flamegraph](flamegraph.md)' >> docs/src/SUMMARY.md

    - name: Build mdBook
      run: |
        cd docs
        mdbook build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/book

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Add Flamegraph results" || echo "No changes to commit"
        git push origin HEAD:main

  deploy:
    needs: flamegraph
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

